worker_processes auto;


events {
  worker_connections 1024;
}

http {
  server_tokens off;
 
  server {
    listen 80;

    location /static/ {
      alias /var/www/;
      autoindex on;

      sendfile on;
      tcp_nopush on;
      sendfile_max_chunk 1m;
    }

  }
}
